global:
  mtls:
    enabled: false
  # Provides dns resolution for global services
  podDNSSearchNamespaces:
  - global
  - "[[ valueOrDefault .DeploymentMeta.Namespace \"default\" ]].global"

  multiCluster:
    enabled: true

  controlPlaneSecurityEnabled: true

# Multicluster with gateways requires a root CA
# Cluster local CAs are bootstrapped with the root CA.
security:
  selfSigned: false

# Provides dns resolution for service entries of form
# name.namespace.global
istiocoredns:
  enabled: true

gateways:
  istio-egressgateway:
    enabled: true
    env:
      # Needed to route traffic via egress gateway if desired.
      ISTIO_META_REQUESTED_NETWORK_VIEW: "external"

mixer:
  telemtery:
    autoscaleEnabled: false

pilot:
  env:
    PILOT_ENABLE_FALLTHROUGH_ROUTE: 1

sidecarInjectorWebhook:
  rewriteAppHTTPProbe: true

prometheus:
  enabled: true

grafana:
  enabled: true

kiali:
  enabled: true
  dashboard:
    grafanaURL: http://grafana:3000

tracing:
  enabled: true

jaeger:
  enabled: true